load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "install_for_bazel",
    srcs = ["bazel/install.sh"],
)

# Shared linter targets from tools/OpenROAD
alias(
    name = "fix_lint",
    actual = "//tools/OpenROAD:fix_lint",
    visibility = ["//visibility:public"],
)

alias(
    name = "lint_test",
    actual = "//tools/OpenROAD:lint_test",
    visibility = ["//visibility:public"],
)
